language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chientm95/docker_experiment -f Dockerfile.dev .

script:
  - docker run -e CI=true chientm95/docker_experiment npm run test